### ISSUE TITLE
Code - vnops

### ISSUE THREAD

**Issue by whoulbool** [grayed/mirea-os-cw#1]
int cwfs_kqfilter(void *v); /*  *v Это же указатель на объект vnode? */

**Comment by grayed** [comment]
См. код этой функции:
```c
int
cwfs_kqfilter(void *v)
{
        struct vop_kqfilter_args *ap = v;
        struct vnode *vp = ap->a_vp;
        struct knote *kn = ap->a_kn;
```
То есть у этого callback'а, если можно так выразиться, поведение такое же, как у остальных: передаётся указатель, который кастуется к соответствующей структуре, уже внутри которой имеется, среди прочего `struct vnode *vp`. Почему не передаётся сразу указатель нужного типа? — в основном, это наследие старых времён. Очень старых. Старее вас, во всяком случае, точно. ;-)

**Comment by whoulbool** [comment]
Понял. А откуда берётся этот указатель с такой переменной, не вижу его объявления

**Comment by grayed** [comment]
В смысле, «где объявили»? Эту вашу функцию вызывает VFS внутри `VOP_KQFILTER(9)`, когда появляется запрос на подписку об изменениях в данной vnode. Тот, кто вызывает, тот и формирует структуру, на которую передаёт указатель.

**Comment by grayed** [comment]
Вроде бы разобрались
